Repository UwUClub/Zappy, pull requests merged in 2023-06, with the labels that each got.

#39 Add 'pgt' event on server
  src/server/implementation/ia/take.c
Labels: enhancement

#48 ZAP-63-tna
  src/gui/cli/ClientApi.cpp
  src/gui/cli/ClientApi.hpp
  src/server/implementation/ia/take.c
  test/testCommandGuiCli.cpp
Labels: enhancement

#51 Add the ```plv``` command and the tests
  src/gui/cli/ClientApi.cpp
  src/gui/cli/ClientApi.hpp
  test/testCommandGuiCli.cpp
Labels: enhancement

#55 Zap 18 Look
  Dependencies.cmake
  doxyfile
  src/ia/main.py
  src/ia/player.py
  src/server/CMakeLists.txt
  src/server/implementation/check_player_on_tile.c
  src/server/implementation/player/cmd/inventory.c
  src/server/implementation/player/cmd/look.c
  src/server/implementation/player/player_cmd_scheduler.c
  src/server/include/core.h
  src/server/include/implementation/implementation.h
  src/server/include/implementation/player_cmd.h
Labels: enhancement

#52 Zap 40 pdr
  src/server/core/write_to_client.c
  src/server/implementation/check_player_on_tile.c
  src/server/implementation/player/cmd/look.c
  src/server/implementation/player/cmd/set.c
  src/server/implementation/player/cmd/take.c
  src/server/include/core.h
Labels: enhancement

#58 Fix Forward
  src/server/CMakeLists.txt
  src/server/implementation/player/cmd/forward.c
  src/server/implementation/player/cmd/look.c
  src/server/include/utils.h
  src/server/utils/calc_outbound.c
Labels: bug

#60 Add ```suc``` command
  src/gui/cli/ClientApi.cpp
Labels: enhancement

#57 Zap 109 food consumption + ZAP 42 pdi
  src/server/CMakeLists.txt
  src/server/core/clients_lifecycle.c
  src/server/core/get_next_timeout.c
  src/server/core/handle_clients.c
  src/server/core/write_to_client.c
  src/server/implementation/player/handle_pending_cmd.c
  src/server/implementation/player/handle_player_digestion.c
  src/server/implementation/player/kill_player.c
  src/server/include/core.h
  src/server/include/implementation/implementation.h
  src/server/include/implementation/player_cmd.h
  src/server/include/resources.h
Labels: enhancement

#62 Add the ```sgt``` command
  src/gui/cli/ClientApi.cpp
  src/gui/cli/ClientApi.hpp
Labels: enhancement

#54 ZAP 99 Connect_nbr
  src/ia/main.py
  src/ia/player.py
  src/server/CMakeLists.txt
  src/server/implementation/player/cmd/connect_nbr.c
  src/server/implementation/player/player_cmd_scheduler.c
  src/server/include/implementation/player_cmd.h
Labels: enhancement

#59 Add the ```pnw``` command
  src/gui/cli/ClientApi.cpp
  src/gui/cli/ClientApi.hpp
  src/gui/cli/Player.cpp
  src/gui/cli/Player.hpp
Labels: enhancement

#64 Add regular resource spawn
  src/server/core/get_next_timeout.c
  src/server/core/handle_clients.c
  src/server/core/server_data.c
  src/server/core/spawn_resources.c
  src/server/include/core.h
  src/server/include/resources.h
Labels: enhancement

#65 Add pnw on server (+fix pdi)
  src/server/CMakeLists.txt
  src/server/core/handle_client_quit.c
  src/server/core/handle_clients.c
  src/server/core/read_client.c
  src/server/core/write_to_client.c
  src/server/implementation/player/append_player_client.c
  src/server/implementation/player/cmd/inventory.c
  src/server/implementation/player/kill_player.c
  src/server/include/core.h
Labels: enhancement

#68 Add pin on server
  src/server/CMakeLists.txt
  src/server/implementation/gui/cmd/pin.c
  src/server/implementation/gui/gui_cmd_executor.c
  src/server/implementation/player/get_player_by_id.c
  src/server/include/implementation/gui_cmd.h
  src/server/include/implementation/implementation.h
Labels: enhancement

#70 Add ppo on server
  src/server/CMakeLists.txt
  src/server/implementation/gui/cmd/ppo.c
  src/server/implementation/gui/gui_cmd_executor.c
  src/server/implementation/player/cmd/right.c
  src/server/include/implementation/gui_cmd.h
Labels: bug, enhancement

#67 Zap 66 pin
  src/gui/CMakeLists.txt
  src/gui/cli/ClientApi.cpp
  src/gui/cli/ClientApi.hpp
  src/gui/cli/ItemPacket.hpp
  src/gui/cli/ParserData.cpp
  src/gui/cli/Player.cpp
  src/gui/cli/Player.hpp
  src/gui/cli/ServerData.cpp
  src/gui/cli/ServerData.hpp
  src/gui/main.cpp
  src/server/core/launch_server.c
  test/CMakeLists.txt
  test/testCommandGuiCli.cpp
Labels: enhancement

#72 Add sst command
  src/server/CMakeLists.txt
  src/server/implementation/gui/cmd/sst.c
  src/server/implementation/gui/gui_cmd_executor.c
  src/server/include/implementation/gui_cmd.h
Labels: enhancement

#63 Add ```sst``` command
  src/gui/cli/ClientApi.cpp
  src/gui/cli/ClientApi.hpp
Labels: enhancement

#80 Fix github probleme
  src/gui/App.cpp
  src/gui/cli/ClientApi.cpp
  src/gui/cli/PlayerData.cpp
Labels: bug

#83 Zap 12 display world
  src/gui/App.cpp
  src/gui/App.hpp
  src/gui/cli/ClientApi.cpp
  src/gui/cli/ClientApi.hpp
  src/gui/cli/PlayerData.cpp
  src/gui/cli/PlayerData.hpp
Labels: enhancement

#85 Added orientation on spawn
  src/gui/App.cpp
  src/gui/App.hpp
  src/gui/Constexpr.hpp
  src/gui/cli/PlayerData.hpp
  src/gui/handlers/events/CameraHandler.hpp
  src/gui/handlers/events/ClickHandler.cpp
Labels: enhancement

#88 Add error handling on set and take command
  src/server/implementation/player/cmd/set.c
  src/server/implementation/player/cmd/take.c
  src/server/include/resources.h
Labels: bug, enhancement

#86 Zap 138 documentation app
  README.md
  src/gui/App.cpp
  src/gui/App.hpp
  src/gui/Subscriber.hpp
  src/gui/handlers/FrameHandler.hpp
  src/gui/handlers/events/CameraHandler.hpp
  src/gui/handlers/events/ClickHandler.hpp
  src/gui/handlers/events/InputHandler.hpp
  src/gui/main.cpp
Labels: documentation

#87 ZAP-134-mouvement-player
  src/gui/App.cpp
  src/gui/App.hpp
  src/gui/cli/ClientApi.cpp
  src/gui/cli/ClientApi.hpp
Labels: enhancement

#78 ZAP 55 Eject
  src/ia/player.py
  src/server/CMakeLists.txt
  src/server/implementation/player/cmd/CMakeLists.txt
  src/server/implementation/player/cmd/eject.c
  src/server/include/implementation/player_cmd.h
Labels: enhancement

#93 Corrected multithreadig issue and added tile
  CMakeLists.txt
  assets/Mesh.mesh.xml
  assets/Rock.material
  assets/Rock.mesh
  assets/Rock_diffuse.png
  assets/Rock_normalMap.png
  copy_resources.sh
  src/gui/App+Listener.cpp
  src/gui/App.cpp
  src/gui/App.hpp
  src/gui/CMakeLists.txt
  src/gui/Constexpr.hpp
Labels: bug, enhancement

#91 Zap 118 pdr
  src/gui/cli/ClientApi.cpp
  src/gui/cli/ClientApi.hpp
  src/gui/cli/ItemPacket.hpp
  src/gui/cli/PlayerData.cpp
  src/gui/cli/PlayerData.hpp
Labels: enhancement

#95 Refactor of the cli and a bit of app
  src/gui/App+Listener.cpp
  src/gui/App.cpp
  src/gui/App.hpp
  src/gui/cli/ClientApi.cpp
  src/gui/cli/PlayerData.cpp
  src/gui/cli/PlayerData.hpp
Labels: documentation, enhancement

#94 Zap 35 pex
  src/server/core/CMakeLists.txt
  src/server/core/normalize_pos.c
  src/server/implementation/egg/hatch_egg.c
  src/server/implementation/gui/cmd/CMakeLists.txt
  src/server/implementation/gui/cmd/pex.c
  src/server/implementation/player/cmd/eject.c
  src/server/implementation/player/cmd/forward.c
  src/server/implementation/player/get_player_by_id.c
  src/server/implementation/player/handle_pending_cmd.c
  src/server/include/core/core.h
  src/server/include/implementation/gui_cmd.h
  src/server/include/implementation/implementation.h
  src/server/include/implementation/player_cmd.h
Labels: bug, enhancement

#99 ZAP-123-edi
  src/gui/cli/ClientApi.cpp
  src/gui/cli/ClientApi.hpp
Labels: enhancement

#98 ZAP-120-pdi
  src/gui/cli/ClientApi.cpp
  src/gui/cli/ClientApi.hpp
Labels: enhancement

#97 ZAP-119-pgt
  src/gui/cli/ClientApi.cpp
  src/gui/cli/ClientApi.hpp
Labels: enhancement

#101 Send pnw list when new gui connects
  src/server/implementation/gui/append_gui_client.c
  src/server/implementation/gui/cmd/pnw.c
  src/server/include/implementation/gui_cmd.h
Labels: enhancement

#102 Zap 145 init all server data information in gui
  assets/Egg.mesh
  assets/Egg.mesh.xml
  assets/LG_leaf.material
  assets/blender2ogre.scene
  assets/bran.jpeg
  assets/bran_b.jpeg
  assets/branches.material
  assets/color2.jpeg
  assets/hedge1_c.jpeg
  src/gui/App+Listener.cpp
  src/gui/App.cpp
  src/gui/App.hpp
  src/gui/cli/ClientApi.cpp
  src/gui/cli/EggData.cpp
  src/gui/cli/EggData.hpp
  src/server/include/resources.h
  test/CMakeLists.txt
Labels: enhancement

#103 Zap 139 parser of look command
  src/ia/main.py
  src/ia/player.py
Labels: enhancement

#104 Add the parser of inventory and remove debug print on look parser
  src/ia/main.py
  src/ia/player.py
Labels: bug, enhancement

#106 Zap 148 fix g UI listener
  assets/Egg.blend
  assets/Egg.material
  assets/Egg.mesh.xml
  assets/LG_leaf.material
  assets/Mesh.mesh.xml
  assets/Rock.blend
  assets/Rock.material
  assets/blender2ogre.scene
  assets/bran.jpeg
  assets/bran_b.jpeg
  assets/branches.material
  assets/color2.jpeg
  assets/hedge1_c.jpeg
  fork_bomb.sh
  src/gui/App+Listener.cpp
  src/gui/App.cpp
  src/gui/App.hpp
  src/gui/CMakeLists.txt
  src/gui/Constexpr.hpp
  src/gui/Observer.hpp
  src/gui/Subscriber.hpp
  src/gui/cli/CMakeLists.txt
  src/gui/cli/ClientApi.cpp
  src/gui/cli/ClientApi.hpp
  src/gui/cli/Observable.cpp
  src/gui/cli/Observable.hpp
  test/CMakeLists.txt
Labels: bug, fix

#107 Zap 142 set and get time
  assets/BTTF.ttf
  install_ogre.sh
  src/gui/App+Listener.cpp
  src/gui/App.cpp
  src/gui/App.hpp
  src/gui/Button.cpp
  src/gui/Button.hpp
  src/gui/CMakeLists.txt
  src/gui/Constexpr.hpp
  src/gui/Observer.hpp
  src/gui/cli/ClientApi.cpp
  src/gui/cli/Observable.cpp
  src/gui/cli/Observable.hpp
  src/gui/handlers/events/ClickHandler.cpp
  src/gui/handlers/events/ClickHandler.hpp
Labels: enhancement

#108 Zap 152 fix server incantation and ia command
  src/ia/main.py
  src/ia/player.py
  src/server/implementation/player/check_player_on_tile.c
  src/server/implementation/player/cmd/broadcast/broadcast.c
  src/server/implementation/player/cmd/incantation/check_tile_for_incantation.c
  src/server/implementation/player/cmd/incantation/incantation.c
  src/server/include/implementation/player_cmd.h
Labels: fix

#109 Zap 149 fix server crash too much connections
  src/server/core/handle_client_quit.c
  src/server/core/handle_clients.c
  src/server/core/launch_server.c
  src/server/core/options/parse_options.c
  src/server/core/read_client.c
  src/server/core/server_data/init_server_data.c
  src/server/core/welcome_single_client.c
  src/server/implementation/gui/cmd/sgt.c
  src/server/implementation/gui/cmd/sst.c
  src/server/implementation/player/cmd/take.c
  src/server/include/core/core.h
  src/server/include/implementation/gui_cmd.h
  src/server/include/ranges.h
  src/server/include/resources.h
  src/server/main.c
Labels: enhancement, fix

#111 Zap 153 fix pdi and enhance file hierarchy
  src/server/core/CMakeLists.txt
  src/server/core/clients/CMakeLists.txt
  src/server/core/clients/clients_lifecycle.c
  src/server/core/clients/handle_client_quit.c
  src/server/core/clients/handle_clients.c
  src/server/core/clients/read_client.c
  src/server/core/clients/welcome_single_client.c
  src/server/core/clients/write_to_client.c
  src/server/core/single_client_lifecycle.c
  src/server/implementation/CMakeLists.txt
  src/server/implementation/game_logic/CMakeLists.txt
  src/server/implementation/game_logic/detect_win.c
  src/server/implementation/game_logic/get_next_timeout.c
  src/server/implementation/game_logic/spawn_resources.c
  src/server/implementation/gui/cmd/CMakeLists.txt
  src/server/implementation/gui/cmd/pdi.c
  src/server/implementation/normalize_pos.c
  src/server/include/implementation/gui_cmd.h
Labels: enhancement, fix

#112 Fix broadcast dir calculation
  src/server/implementation/player/cmd/broadcast/get_tile_from_source.c
Labels: fix

#113 Added how to play
  assets/BTTF.ttf
  src/gui/App.cpp
  src/gui/App.hpp
  src/gui/Button.cpp
  src/gui/Button.hpp
  src/gui/Constexpr.hpp
  src/gui/SceneBuilder.cpp
  src/gui/SceneBuilder.hpp
  src/gui/handlers/events/InputHandler.cpp
Labels: documentation, enhancement, fix

#115 Fix crash on player death
  src/server/core/clients/handle_client_quit.c
  src/server/core/clients/handle_clients.c
  src/server/core/clients/write_to_client.c
  src/server/include/core/core.h
Labels: fix

#119 Added first animation for incantation
  assets/Rock.blend
  assets/Rock.material
  assets/Sinbad.blend
  assets/Sinbad.material
  assets/Sinbad.mesh
  assets/Sinbad.skeleton
  assets/Sword.mesh
  assets/sinbad_body.tga
  assets/sinbad_clothes.tga
  assets/sinbad_sword.tga
  assets/skybox.zip
  src/gui/App+Listener.cpp
  src/gui/App.cpp
  src/gui/App.hpp
  src/gui/Constexpr.hpp
  src/gui/Mediator.cpp
  src/gui/Mediator.hpp
  src/gui/cli/ClientApi+Listener.cpp
  src/gui/cli/ClientApi.cpp
  src/gui/cli/ClientApi.hpp
  src/gui/handlers/AnimationHandler.cpp
  src/gui/handlers/AnimationHandler.hpp
  src/gui/handlers/CMakeLists.txt
Labels: enhancement

#118 Zap 143 server unit tests
  src/server/core/clients/handle_client_quit.c
  src/server/implementation/gui/cmd/pin.c
  src/server/implementation/gui/cmd/plv.c
  src/server/implementation/gui/cmd/ppo.c
  src/server/implementation/player/cmd/incantation/incantation.c
  src/server/implementation/player/get_player_by_id.c
  src/server/include/core/core.h
  src/server/include/implementation/implementation.h
  src/server/utils/concat_str.c
  src/server/utils/int_to_s.c
  test/gui/CMakeLists.txt
  test/gui/testCommandGuiCli.cpp
  test/server/CMakeLists.txt
  test/server/calcOutbound.cpp
  test/server/concatStr.cpp
  test/server/concatWordArray.cpp
  test/server/getPlayerById.cpp
  test/server/intToS.cpp
  test/server/isInt.cpp
  test/server/isIp.cpp
  test/server/isPlayer.cpp
  test/server/normalizePos.cpp
  test/server/revStr.cpp
Labels: enhancement

#120 Added idle animation
  src/gui/App+Listener.cpp
  src/gui/App.cpp
  src/gui/App.hpp
  src/gui/handlers/AnimationHandler.cpp
  src/gui/handlers/AnimationHandler.hpp
Labels: enhancement

#121 Zap 164 remake of units tests
  CMakeLists.txt
  test/CMakeLists.txt
  test/testCommandGuiCli.cpp
Labels: enhancement, test

#122 Add and use EXIT_STATUS and ERROR_STATUS macros
  src/server/core/clients/handle_clients.c
  src/server/core/clients/write_to_client.c
  src/server/core/launch_server.c
  src/server/core/options/map_setters.c
  src/server/core/options/option_setters.c
  src/server/core/options/parse_options.c
  src/server/implementation/game_logic/detect_win.c
  src/server/implementation/gui/append_gui_client.c
  src/server/implementation/gui/cmd/bct.c
  src/server/implementation/gui/cmd/msz.c
  src/server/implementation/gui/cmd/pdr.c
  src/server/implementation/gui/cmd/pex.c
  src/server/implementation/gui/cmd/pin.c
  src/server/implementation/gui/cmd/plv.c
  src/server/implementation/gui/cmd/ppo.c
  src/server/implementation/gui/cmd/seg.c
  src/server/implementation/gui/cmd/sgt.c
  src/server/implementation/gui/cmd/sst.c
  src/server/implementation/gui/cmd/tna.c
  src/server/implementation/gui/gui_cmd_executor.c
  src/server/implementation/input_parser.c
  src/server/implementation/player/append_player_client.c
  src/server/implementation/player/cmd/broadcast/broadcast.c
  src/server/implementation/player/cmd/connect_nbr.c
  src/server/implementation/player/cmd/eject.c
  src/server/implementation/player/cmd/fork.c
  src/server/implementation/player/cmd/forward.c
  src/server/implementation/player/cmd/incantation/check_tile_for_incantation.c
  src/server/implementation/player/cmd/incantation/incantation.c
  src/server/implementation/player/cmd/inventory.c
  src/server/implementation/player/cmd/left.c
  src/server/implementation/player/cmd/look.c
  src/server/implementation/player/cmd/pgt.c
  src/server/implementation/player/cmd/right.c
  src/server/implementation/player/cmd/set.c
  src/server/implementation/player/cmd/take.c
  src/server/implementation/player/is_player.c
  src/server/implementation/player/player_cmd_scheduler.c
  src/server/include/core/core.h
  src/server/include/implementation/player_cmd.h
  src/server/main.c
  test/server/test_zappy
Labels: enhancement

#124 Zap 163 animations
  assets/Skybox.material
  assets/skybox.zip
  assets/stevecube_bk.jpg
  assets/stevecube_dn.jpg
  assets/stevecube_fr.jpg
  assets/stevecube_lf.jpg
  assets/stevecube_rt.jpg
  assets/stevecube_up.jpg
  src/gui/App+Listener.cpp
  src/gui/App.cpp
  src/gui/App.hpp
  src/gui/SceneBuilder.cpp
  src/gui/SceneBuilder.hpp
  src/gui/cli/ClientApi.cpp
  src/gui/handlers/AnimationHandler.cpp
  src/gui/handlers/AnimationHandler.hpp
  test/CMakeLists.txt
Labels: documentation, enhancement, fix, refactor

#127 Zap 168 add mct + enhance resources
  src/server/implementation/game_logic/spawn_resources.c
  src/server/implementation/gui/append_gui_client.c
  src/server/implementation/gui/cmd/CMakeLists.txt
  src/server/implementation/gui/cmd/bct.c
  src/server/implementation/gui/cmd/mct.c
  src/server/implementation/player/cmd/incantation/incantation.c
  src/server/implementation/player/cmd/set.c
  src/server/implementation/player/cmd/take.c
  src/server/include/implementation/gui_cmd.h
  src/server/include/resources.h
Labels: enhancement

#125 Improve ppo / pnw + send pin on connection / inventory update
  src/server/implementation/gui/append_gui_client.c
  src/server/implementation/gui/cmd/ebo.c
  src/server/implementation/gui/cmd/enw.c
  src/server/implementation/gui/cmd/pin.c
  src/server/implementation/gui/cmd/pnw.c
  src/server/implementation/gui/cmd/ppo.c
  src/server/implementation/player/append_player_client.c
  src/server/implementation/player/cmd/fork.c
  src/server/implementation/player/handle_player_digestion.c
  src/server/include/implementation/gui_cmd.h
Labels: enhancement, fix

#128 Zap 169 create background of texts
  assets/Inventory.png
  assets/Textbox.png
  assets/textbox.material
  src/gui/App.cpp
  src/gui/Button.cpp
  src/gui/Constexpr.hpp
  src/gui/Inventory.cpp
  src/gui/cli/ItemPacket.cpp
Labels: enhancement

#129 Zap 163 animations
  assets/stevecube_bk.jpg
  assets/stevecube_dn.jpg
  assets/stevecube_fr.jpg
  assets/stevecube_lf.jpg
  assets/stevecube_rt.jpg
  assets/stevecube_up.jpg
  src/gui/App+Listener.cpp
  src/gui/App.cpp
  src/gui/App.hpp
  src/gui/SceneBuilder.cpp
  src/gui/SceneBuilder.hpp
  src/gui/handlers/AnimationHandler.cpp
  src/gui/handlers/CMakeLists.txt
  src/gui/handlers/MovementHandler.cpp
  src/gui/handlers/MovementHandler.hpp
  test/CMakeLists.txt
Labels: documentation, enhancement

#132 I hope it will work
  src/gui/App+Listener.cpp
  src/gui/App.cpp
  src/gui/App.hpp
Labels: bug, fix

#131 Zap 133 basic ai evolving to level 8
  src/gui/App+Listener.cpp
  src/gui/App.cpp
  src/gui/App.hpp
  src/gui/Constexpr.hpp
  src/gui/SceneBuilder.cpp
  src/gui/cli/ClientApi+Listener.cpp
  src/gui/cli/ItemPacket.cpp
  src/ia/player.py
  src/server/implementation/gui/cmd/pdr.c
  src/server/implementation/player/cmd/broadcast/broadcast.c
  src/server/implementation/player/cmd/broadcast/get_tile_from_source.c
  src/server/implementation/player/cmd/incantation/CMakeLists.txt
  src/server/implementation/player/cmd/incantation/incantation.c
  src/server/implementation/player/cmd/incantation/player_actions.c
  src/server/implementation/player/cmd/look.c
  src/server/implementation/player/cmd/pgt.c
  src/server/implementation/player/cmd/take.c
  src/server/include/implementation/player_cmd.h
Labels: enhancement

#133 Zap 155 create unit tests
  src/ia/__init__.py
  src/ia/iaParser.py
  src/ia/main.py
  src/ia/player.py
  src/ia/test/__init__.py
  src/ia/test/test.py
Labels: test

#136 Fix merge dev
  src/ia/player.py
Labels: fix

#137 Fixed bad merging
  src/gui/App+Listener.cpp
  src/gui/App.cpp
  src/gui/SceneBuilder.cpp
  src/gui/SceneBuilder.hpp
  src/gui/handlers/MovementHandler.cpp
Labels: bug, fix

#138 Fix probleme on dev
  src/gui/App+Listener.cpp
  src/gui/App.cpp
  src/gui/SceneBuilder.cpp
  src/gui/SceneBuilder.hpp
  src/gui/handlers/MovementHandler.cpp
  src/ia/player.py
Labels: enhancement

#140 Dev to Main
  src/gui/Inventory.cpp
Labels: enhancement

#141 Zap 133 basic ai evolving to level 8
  src/ia/player.py
Labels: enhancement, fix

#144 Fix remote connection to server
  src/gui/cli/ParserData.cpp
Labels: enhancement
